config/routes.rb
Rails.application.routes.draw do  

  resources :listings, except: :index do
    resources :bids, only: [:create, :new, :destroy] do
      member do
        post :confirm
      end
    end
  end
  
  get 'landing/index'

  root 'landing#index'

  devise_for :users, controllers: {registrations: 'registrations'}
  resources :users, :only => [:show] do
    member do
      get :profile
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bid.rb
class Bid < ApplicationRecord
  belongs_to :user
  belongs_to :listing

  #paper clip image upload
  has_attached_file :image, styles: { small: "64x64", med: "100x100", large: "200x200" }
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :user
  has_many :bids
  belongs_to :confirmed_bid, class_name: 'Bid'
  #paper clip image upload
  has_attached_file :image, styles: { small: "64x64", med: "100x100", large: "200x200" }
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/models/user.rb
class User < ApplicationRecord
  has_many :listings, dependent: :destroy
  has_many :bids, through: :listings

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :profile_pic, styles: { small: "64x64", med: "100x100", large: "200x200" }

  # Only allow letter, number, underscore and punctuation.
  validates_format_of :username, with: /^[a-zA-Z0-9_\.]*$/, :multiline => true
  validates_uniqueness_of :username
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  include Pundit
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :name])
  end

end

app/controllers/bids_controller.rb
class BidsController < ApplicationController
  def new
    @listing = Listing.find(params[:listing_id])
    @bid = Bid.new
  end

  def create
    @listing = Listing.find(params[:listing_id])
    @bid = @listing.bids.new(bid_params)
    @bid.user = current_user

    if @bid.save
      flash[:notice] = "New bid added."
      redirect_to @listing
    else
      flash.now[:alert] = "Something went wrong creating the bid."
      render :new
    end
  end

  def confirm
    @listing = Listing.find(params[:listing_id])
    @listing.confirmed_bid = @listing.bids.find(params[:id])

    if @listing.save
      flash[:notice] = "Confimed Bid!."
    else
      flash.now[:alert] = "Something went wrong confirming the bid."
    end
    redirect_to @listing
  end

  private
  def bid_params
    params.require(:bid).permit(:price , :description, :image)
  end

end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def index
    @listings = Listing.all
  end

  def show
    @listing = Listing.find(params[:id])
    @user = User.find(params[:id])
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :authenticate_user!

  def index
    @listings = Listing.where(confirmed_bid_id: nil)
  end

  def show
    @listing = Listing.find(params[:id])
    @bids = @listing.bids
  end

  def new
    @listing = Listing.new
  end

  def create
    @listing = current_user.listings.new(listing_params)
 
    if @listing.save
      flash[:notice] = "New listing added."
      redirect_to @listing
    else
      flash.now[:alert] = "Something went wrong creating the listing."
      render :new
    end
  end

  def edit
    @listing = Listing.find(params[:id])
    authorize @listing
  end

  def update
    @listing = Listing.find(params[:id])
    authorize @listing
 
    @listing.assign_attributes(listing_params)
 
    if @listing.save
      flash[:notice] = "listing was updated."
      redirect_to @listing
    else
      flash.now[:alert] = "Error saving listing. Please try again."
      render :edit
    end
  end

  def destroy
    @listing = Listing.find(params[:id])
    authorize @listing
 
    if @listing.destroy
      flash[:notice] = "\"#{@listing.title}\" was deleted successfully."
      redirect_to action: :index
    else
      flash.now[:alert] = "There was an error deleting the listing."
      render :show
    end
  end

  def confirm_bid
    @listing = Listing.find(params[:id])
    @listing.confirmed_bid = Bid.find(params[:bid_id])

    if @listing.save
      flash[:notice] = "Bid was confirmed."
    else
      flash.now[:alert] = "Error saving confirmed bid. Please try again."
    end
    redirect_to @lisitng
  end

  private
  def listing_params
    params.require(:listing).permit(:title, :image, :description, :location, :asking_price)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :username, :password, :password_confirmation, :contact_number, :location, :rating)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def profile
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bids_helper.rb
module BidsHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/bids/_bid.html.erb
<div class="media">
  <div class="media-body">
  <% if current_user == @listing.user && @listing.confirmed_bid == nil %>
     <%= button_to('Confirm', confirm_listing_bid_path(@listing, bid), :method => :post, data: {confirm: "Are you sure you want to Confirm this bid?"}, :class => 'btn btn-large btn-primary') %>
  <% end %>
  <% if bid == @listing.confirmed_bid %>
    Confirmed Bid
  <% end %>
      <h4 class="media-heading">
      <%= link_to bid.user.username, profile_user_path(bid.user) %>
    </h4>
      <p><%= bid.price %></p>
      <p><%= image_tag bid.image.url(:med) %></p>
      <p><%= bid.description %></p>
  </div>
</div>

app/views/bids/new.html.erb
<h1>Place Bid</h1>
<div class="row">
   <div class="col-md-8">
     <%= form_for [@listing, @bid], html: { multipart: true } do |f| %>
       <div class="form-group">
         <%= f.label :price %>
         <%= f.text_field :price, class: 'form-control', placeholder: "Place Your Price" %>
       </div>
       <div class="form-group">
         <%= f.label :image  %>
         <%= f.file_field :image, class: 'form-control' %>
       </div>
       <div class="form-group">
         <%= f.label :description %>
         <%= f.text_area :description, rows: 8, class: 'form-control', placeholder: "Enter item description, New, used, etc." %>
       </div>
       <%= f.submit "Save", class: 'btn btn-success' %>
     <% end %>
   </div>
 </div>

app/views/landing/_marketplace.html.erb
<div class="container">
    <div class="row">
      <div class="listing-content">
        <div class="well">
          <%= render partial: "listings/listing", collection: @listings %>
        </div>
      </div>
    </div>
  </div>

app/views/landing/index.html.erb
<div id="landing">
  <div id="landing-caption">
    <h1 class="display-3">FlipBuy</h1>
    <p>You want it, they sell it.</p>
    <% if user_signed_in? %>
      <h4><%= current_user.username %></h4>
    <% else %>
      <%= button_to('Get Started', new_user_registration_path, :method => :get, :class => 'btn btn-large btn-success') %>
    <% end %>
  </div>
</div>

<section id="marketplace">
  <%= render partial: "landing/marketplace" %>
</section>

app/views/layouts/_messages.html.erb
 <% if flash[:notice] %>
   <div class="alert alert-success">
     <button type="button" class="close" data-dismiss="alert">&times;</button>
     <%= flash[:notice] %>
   </div>
 <% elsif flash[:alert] %>
   <div class="alert alert-warning">
     <button type="button" class="close" data-dismiss="alert">&times;</button>
     <%= flash[:alert] %>
   </div>
 <% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-toggleable-md navbar-light bg-faded navbar-fixed-top">
  <%= link_to "Logo", root_path, class: 'navbar-brand' %>
  <ul class="nav navbar-nav pull-sm-right">
    <% if user_signed_in? %>
      <li class="nav-item">
        <%= link_to 'Want Something?', new_listing_path %>
      </li>
      <li class="nav-item">
        <%= link_to 'Profile', profile_user_path(current_user) %>
      </li>
      <li class="nav-item">
        <%= button_to('Sign out', destroy_user_session_path, :method => :delete, :class => 'btn btn-large btn-primary') %>
      </li>
    <% else %>
      <li class="nav-item">
        <%= link_to "Sign In", new_user_session_path %>
      </li>
      <li class="nav-item">
        <%= button_to('Sign Up', new_user_registration_path, :method => :get, :class => 'btn btn-large btn-primary') %>
      </li>
    <% end %>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlipBuy</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>

    <div class="container">
       <%= render 'layouts/messages' %>
    </div>
    <%= yield %>
    
  </body>
</html>

app/views/listings/_listing.html.erb
<div class="media">
  <div class="media-body">
    <h4 class="media-heading">
      <%= link_to listing.title, listing_path( :id => listing.id ) %>
    </h4>
      <p><%= image_tag listing.image.url(:med) %></p>
      <p><%= listing.asking_price %></p>
  </div>
</div>

app/views/listings/index.html.erb
<section id="marketplace">
  <div class="container">
    <div class="row">
      <div class="listing-content">
        <div class="well">
          <h1>Listings</h1>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/listings/new.html.erb
<h1>New Listing</h1>
<div class="row">
   <div class="col-md-8">
     <%= form_for @listing, html: { multipart: true } do |f| %>
       <div class="form-group">
         <%= f.label :title %>
         <%= f.text_field :title, class: 'form-control', placeholder: "Title" %>
       </div>
       <div class="form-group">
         <%= f.label :image  %>
         <%= f.file_field :image, class: 'form-control' %>
       </div>
       <div class="form-group">
         <%= f.label :description %>
         <%= f.text_area :description, rows: 8, class: 'form-control', placeholder: "Enter item description, New, used, etc." %>
       </div>
        <div class="form-group">
         <%= f.label :location %>
         <%= f.text_field :location, class: 'form-control', placeholder: "Current Location" %>
       </div>
        <div class="form-group">
         <%= f.label :asking_price %>
         <%= f.text_field :asking_price, class: 'form-control', placeholder: "How much you want it for" %>
       </div>
       <%= f.submit "Save", class: 'btn btn-success' %>
     <% end %>
   </div>
 </div>

app/views/listings/show.html.erb
 <div class="row">
   <div class="col-md-6">
     <h1><%= @listing.title %></h1>
     <p><%= @listing.description %></p>
     <p><%= image_tag @listing.image.url(:large) %></p>
     <p><%= @listing.asking_price %></p>
     <p>Posted by <%= @listing.user.username %></p>
      <% if policy(@listing).update? && policy(@listing).destroy? %>
          <%= link_to "Edit post", edit_listing_path(@listing) %>
          <%= button_to "Delete", @listing, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this lsiting?'} %>
      <% end %>
      <% if current_user != @listing.user %>
        <%= link_to "Make a Bid", new_listing_bid_path(@listing) %>
      <% end %>
  </div>

    <div class="col-md-6">
      <div id="bids">
        <h3>Bids</h3>
          <%= render partial: "bids/bid",  collection: @bids %>
      </div>
    </div>

</div>

app/views/users/profile.html.erb
<h1>Profile</h1>
<%= @user.email %>

<%= @user.email %>
<%= @user.username  %>
<%= @user.location %>
<%= @user.contact_number %>
<%= @user.rating %>

app/views/users/show.html.erb
<h1>Hello <%= %></h1>